const data = {
  products: [
    {
      _id: "1",
      name: "Nike Slim Shirt",
      slug: "nike-slim-shirt",
      image: "/images/p1.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "High quality shirt",
    },
    {
      _id: "2",
      name: "Adidas Slim Shirt",
      slug: "adidas-slim-shirt",
      image: "/images/p2.jpg",
      price: 200,
      countInStock: 0,
      brand: "Adidas",
      rating: 4.9,
      numReviews: 11,
      description: "High quality product",
    },
    {
      _id: "3",
      name: "Nike Slim Pant",
      slug: "nike-slim-pant",
      image: "/images/p3.jpg",
      price: 25,
      countInStock: 15,
      brand: "Nike",
      rating: 3,
      numReviews: 14,
      description: "High quality pant",
    },
    {
      _id: "4",
      name: "Adidas Fit Pant",
      slug: "adidas-fit-pant",
      image: "/images/p4.jpg",
      price: 28,
      countInStock: 9,
      brand: "Adidas",
      rating: 4.0,
      numReviews: 2,
      description: "High quality product",
    },
  ],
};

export default data;
